version: "3"

services:
  webserver:
    image: html-photo-frame/test-webserver
    build:
      dockerfile: ./cypress/docker/webserver.Dockerfile
      context: ../..
    container_name: webserver
    tty: true
    ports:
      - "9080:9080"
    volumes:
      - ../..:/app

  cypress:
    image: html-photo-frame/cypress
    build:
      dockerfile: ./cypress/docker/cypress.Dockerfile
      context: ../..
    container_name: cypress
    depends_on:
      - webserver
    entrypoint: cypress run --config-file cypress/config.js
    environment:
      - CYPRESS_baseUrl=http://webserver:9080
    volumes:
      - ../..:/app
