version: "3"

services:
  webserver:
    image: webserver
    build:
      dockerfile: ./cypress/docker/webserver.Dockerfile
      context: ../..
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "8080:9080"
    volumes:
      - ../..:/app

  cypress:
    image: cypress
    build:
      dockerfile: ./cypress/docker/cypress.Dockerfile
      context: ../..
    container_name: cypress
    stdin_open: true
    tty: true
    environment:
      - CYPRESS_baseUrl=http://webserver:9080
    volumes:
      - ../..:/app
